# Generated by Django 4.2 on 2025-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_rollno', models.CharField(max_length=30, unique=True)),
                ('Student_name', models.CharField(max_length=30)),
                ('Father_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('tenth_dmc', models.FileField(blank=True, upload_to='upload/')),
                ('twelth', models.FileField(blank=True, upload_to='upload/')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
