# Generated by Django 4.2 on 2025-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=200),
        ),
    ]
