# Generated by Django 4.2 on 2025-04-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('management', models.CharField(max_length=30)),
                ('economics', models.CharField(max_length=30)),
                ('mathematics', models.CharField(max_length=30)),
                ('accounting', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('computer', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bba',
            },
        ),
        migrations.CreateModel(
            name='BCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('C', models.CharField(max_length=30)),
                ('Digital_Electronics', models.CharField(max_length=30)),
                ('mathematics_I', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('computer', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'bca',
            },
        ),
    ]
