# Generated by Django 5.0.2 on 2026-03-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('course', 'semester')},
        ),
    ]
