# Generated by Django 5.2.8 on 2026-01-04 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=256)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_suspicious', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_and_Admin_Attedance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeID', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('leave_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, unique=True)),
                ('time', models.CharField(max_length=50, unique=True)),
                ('timestamp', models.CharField(max_length=50, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('random_data', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('pic6', models.ImageField(blank=True, null=True, upload_to='pic6/')),
                ('pic7', models.ImageField(blank=True, null=True, upload_to='pic7/')),
                ('pic8', models.ImageField(blank=True, null=True, upload_to='pic8/')),
                ('pic9', models.ImageField(blank=True, null=True, upload_to='pic9/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('content', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='result',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='adjusted_in',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='for_year',
        ),
        migrations.AddField(
            model_name='admin',
            name='attendance_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='admin',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='attendance_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='faculty',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='adjusted_in_semester',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='adjusted_in_year',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='batch',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='structure_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.position'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.position'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentbalance',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='admindocuments',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
        migrations.AddField(
            model_name='facultydocuments',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.faculty'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail'),
        ),
        migrations.AddField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail'),
        ),
    ]
