# Generated by Django 5.0.2 on 2026-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_feestructure_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='batch',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
