# Generated by Django 4.2 on 2025-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
