# Generated by Django 4.2 on 2025-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_bba_bca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bba',
            name='rollno',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bca',
            name='rollno',
            field=models.CharField(max_length=30),
        ),
    ]
