# Generated by Django 4.2 on 2025-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_student_faculty',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
