# Generated by Django 4.2 on 2025-04-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_bba_rollno_alter_bca_rollno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bba',
            table='B.B.A',
        ),
        migrations.AlterModelTable(
            name='bca',
            table='B.C.A',
        ),
    ]
