# Generated by Django 4.2 on 2025-08-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_attendance_student_faculty_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_student_faculty',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
