# Generated by Django 4.2 on 2025-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
