# Generated by Django 5.0.2 on 2026-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_leave_chatmessage_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
