# Generated by Django 5.0.2 on 2026-01-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_leave_applied_on_alter_leave_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave'), ('ML', 'Medical Leave'), ('ON', 'On Duty '), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.TimeField(),
        ),
    ]
