# Generated by Django 4.2 on 2025-04-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_bba_table_alter_bca_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('history', models.CharField(max_length=30)),
                ('political_science', models.CharField(max_length=30)),
                ('sociology', models.CharField(max_length=30)),
                ('psychology', models.CharField(max_length=30)),
                ('economics', models.CharField(max_length=30)),
                ('english_literature', models.CharField(max_length=30)),
                ('hindi', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'B.A',
            },
        ),
        migrations.CreateModel(
            name='B_Com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('Financial_Accounting', models.CharField(max_length=30)),
                ('Business_management', models.CharField(max_length=30)),
                ('mathematics', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('environmental_studies', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'B.Com',
            },
        ),
        migrations.CreateModel(
            name='B_Sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('Physics', models.CharField(max_length=30)),
                ('Chemistry', models.CharField(max_length=30)),
                ('mathematics_I', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('computer', models.CharField(max_length=30)),
                ('Environmental_science', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'B.Sc',
            },
        ),
    ]
