# Generated by Django 4.2 on 2025-08-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_attendance_student_faculty_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance_student_faculty',
            options={'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
    ]
