# Generated by Django 4.2 on 2025-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
