# Generated by Django 4.2 on 2025-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default='AI', max_length=100),
            preserve_default=False,
        ),
    ]
