# Generated by Django 5.0.2 on 2026-01-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_leave_leave_type_alter_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Earned Leave', 'Earned Leave'), ('Medical Leave', 'Medical Leave'), ('On Duty Leave', 'On Duty Leave'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
