# Generated by Django 5.0.2 on 2026-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_leave_leave_type_alter_leave_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
