# Generated by Django 4.2 on 2025-09-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_faculty_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.position'),
        ),
    ]
