# Generated by Django 4.2 on 2025-08-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_attendance_lecture_delete_attendance_student_faculty_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
