# Generated by Django 4.2 on 2025-08-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default='Saini', max_length=100),
            preserve_default=False,
        ),
    ]
