# Generated by Django 4.2 on 2025-07-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='age',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='name',
            new_name='two',
        ),
    ]
