# Generated by Django 4.2 on 2025-08-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_lecture_unique_together_remove_lecture_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='fees_period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='time_per_lecture',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
