# Generated by Django 4.2 on 2025-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_faculty_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='Saini', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan'), ('China', 'China'), ('Other', 'Other')], default='India', max_length=30),
        ),
    ]
