# Generated by Django 5.0.2 on 2026-01-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_userdetail_password_alter_userdetail_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='student_capacity',
        ),
    ]
