# Generated by Django 4.2 on 2025-09-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_staffdocuments_studentdocuments_delete_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic7', to='newapp.studentdocuments'),
        ),
        migrations.AddField(
            model_name='student',
            name='pic8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic8', to='newapp.studentdocuments'),
        ),
    ]
