# Generated by Django 5.0.2 on 2026-01-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_department_type_alter_department_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
    ]
