# Generated by Django 4.2 on 2025-08-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_department_alter_course_department_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees_period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
