# Generated by Django 4.2 on 2025-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_result_delete_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('I', models.CharField(max_length=20)),
                ('II', models.CharField(max_length=20)),
                ('III', models.CharField(max_length=20)),
                ('IV', models.CharField(max_length=20)),
                ('V', models.CharField(max_length=20)),
                ('VI', models.CharField(max_length=20)),
                ('VII', models.CharField(max_length=20)),
                ('VIII', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='B_A',
        ),
        migrations.DeleteModel(
            name='B_Com',
        ),
        migrations.DeleteModel(
            name='B_Sc',
        ),
        migrations.DeleteModel(
            name='BBA',
        ),
        migrations.DeleteModel(
            name='BCA',
        ),
        migrations.AddField(
            model_name='student_add',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='student_add',
            name='semester',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='student_add',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
