# Generated by Django 4.2 on 2025-09-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_student_pic9'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
