# Generated by Django 4.2 on 2025-08-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_alter_course_fees_period_alter_course_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unit',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit_fees',
            field=models.CharField(choices=[('Semester', 'semester'), ('Year', 'year')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='unit_lecture',
            field=models.CharField(choices=[('Hour', 'hour'), ('Min', 'min')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
