# Generated by Django 4.2 on 2025-08-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_department_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='status',
        ),
    ]
