# Generated by Django 5.0.2 on 2026-01-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_department_code_alter_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='no_of_lecture',
            new_name='semesters',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='no_of_semesters',
            new_name='years',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='no_of_years',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=10, verbose_name=[('AI', 'AI'), ('Honours', 'Honours'), 'Genreral']),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
