# Generated by Django 4.2 on 2025-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_subject_i_alter_subject_ii_alter_subject_iii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add',
            name='semester',
            field=models.CharField(default='I', max_length=30),
        ),
    ]
