# Generated by Django 4.2 on 2025-08-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_remove_department_head_of_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_per_lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unit_lecture',
        ),
        migrations.RemoveField(
            model_name='program',
            name='degree',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='2025-06-05', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='2024-09-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='student_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
