# Generated by Django 4.2 on 2025-09-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_admin_permission_faculty_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic1', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic2', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic3', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic4', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic5', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic6',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic6', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic7',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic7', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic8', to='newapp.studentdocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentPic9', to='newapp.studentdocuments'),
        ),
    ]
