# Generated by Django 4.2 on 2025-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_remove_attendance_is_present_remove_course_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timing',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
