# Generated by Django 4.2 on 2025-08-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_attendance_department_attendance_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timing',
        ),
    ]
