# Generated by Django 4.2 on 2025-09-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_alter_student_pic1_alter_student_pic2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pic9',
        ),
        migrations.RemoveField(
            model_name='studentdocuments',
            name='image',
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='pic1/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='pic2/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='pic3/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to='pic4/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic5',
            field=models.ImageField(blank=True, null=True, upload_to='pic5/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic6',
            field=models.ImageField(blank=True, null=True, upload_to='pic6/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic7',
            field=models.ImageField(blank=True, null=True, upload_to='pic7/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic8',
            field=models.ImageField(blank=True, null=True, upload_to='pic8/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='pic9',
            field=models.ImageField(blank=True, null=True, upload_to='pic9/'),
        ),
        migrations.AddField(
            model_name='studentdocuments',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
            preserve_default=False,
        ),
    ]
