# Generated by Django 4.2 on 2025-08-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_level_remove_course_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.level'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
