# Generated by Django 4.2 on 2025-09-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_remove_student_pic1_remove_student_pic2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.student'),
        ),
    ]
