# Generated by Django 4.2 on 2025-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_remove_attendance_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timing',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
