# Generated by Django 4.2 on 2025-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_result_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
