# Generated by Django 5.0.2 on 2026-01-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
