# Generated by Django 4.2 on 2025-09-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_studentdocuments_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='pic1/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='pic2/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='pic3/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='pic4/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='pic5/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pic5',
        ),
        migrations.DeleteModel(
            name='StaffDocuments',
        ),
        migrations.AddField(
            model_name='facultydocuments',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.faculty'),
        ),
        migrations.AddField(
            model_name='admindocuments',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.admin'),
        ),
    ]
