# Generated by Django 4.2 on 2025-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
