# Generated by Django 5.0.2 on 2026-01-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_remove_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='adjusted_in_semester',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='adjusted_in_year',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='extra',
        ),
    ]
