# Generated by Django 4.2 on 2025-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_admindocuments_facultydocuments_remove_admin_pic1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='structure_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
