# Generated by Django 4.2 on 2025-08-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
