# Generated by Django 4.2 on 2025-09-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_feestructure_structure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='structure_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
