# Generated by Django 5.0.2 on 2026-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_remove_feepayment_adjusted_in_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
