# Generated by Django 4.2 on 2025-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_position_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
