# Generated by Django 4.2 on 2025-09-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_feestructure_structure_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='for_year',
            new_name='batch',
        ),
    ]
