# Generated by Django 5.0.2 on 2026-01-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newapp', '0017_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Room', 'Room'), ('Lab', 'Lab')], max_length=10)),
                ('number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('assignment_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=100)),
                ('due_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('late', 'Late Submission')], default='pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('feedback', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='attendance_pin',
            new_name='personal_pin',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='lecture_number',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='attendance_pin',
            new_name='personal_pin',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('college_id', 'lecture', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qr_code',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qr_code',
            name='expiry_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qr_code',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='personal_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Pending', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='faculty_and_admin_attedance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='faculty_and_admin_attedance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Leave', 'Leave'), ('Pending', 'Pending')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Emergency Leave', 'Emergency Leave'), ('Planned Leave', 'Planned Leave'), ('Short Leave', 'Short Leave')], max_length=50),
        ),
        migrations.DeleteModel(
            name='StudentBalance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
    ]
