# Generated by Django 4.2 on 2025-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_position_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='requirment',
            field=models.TextField(),
        ),
    ]
