# Generated by Django 4.2 on 2025-07-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_result_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add',
            name='tenth_dmc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='twelth',
            field=models.CharField(max_length=10),
        ),
    ]
