# Generated by Django 5.0.2 on 2026-01-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newapp', '0017_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('day', models.CharField(default='Monday', max_length=20)),
                ('time', models.TimeField(default='09:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('assignment_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=100)),
                ('due_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('late', 'Late Submission')], default='pending', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('feedback', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentBalance',
        ),
    ]
