# Generated by Django 4.2 on 2025-08-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_feestructure_feepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fees',
            new_name='fees_per_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees_period',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unit_fees',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='is_active',
        ),
    ]
