# Generated by Django 4.2 on 2025-09-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_rename_for_year_feestructure_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='batch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='semester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='structure_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
