# Generated by Django 4.2 on 2025-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_alter_position_requirment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_lecture',
            field=models.IntegerField(default=6),
        ),
    ]
