# Generated by Django 4.2 on 2025-08-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_rename_fees_course_fees_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='fee_structure',
        ),
    ]
