# Generated by Django 5.0.2 on 2026-01-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_schedule_studentassignment_leave_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.department'),
            preserve_default=False,
        ),
    ]
