# Generated by Django 4.2 on 2025-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_alter_feestructure_amount_alter_feestructure_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='adjusted_in',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='adjusted_in_semester',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='adjusted_in_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
