# Generated by Django 5.0.2 on 2026-01-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_alter_leave_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='department_name',
            new_name='department',
        ),
    ]
