# Generated by Django 4.2 on 2025-08-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_remove_feepayment_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.feestructure'),
        ),
    ]
