# Generated by Django 4.2 on 2025-08-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_feepayment_fee_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='for_year',
            field=models.IntegerField(default=2025),
        ),
    ]
