# Generated by Django 5.0.2 on 2026-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_rename_department_name_leave_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(default=''),
        ),
    ]
