# Generated by Django 4.2 on 2025-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
