# Generated by Django 4.2 on 2025-08-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_feestructure_for_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='for_year',
            field=models.IntegerField(),
        ),
    ]
