# Generated by Django 4.2 on 2025-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_alter_feepayment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
