# Generated by Django 4.2 on 2025-08-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_alter_feestructure_for_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='applied_to_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payments', to='newapp.feestructure'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
    ]
