# Generated by Django 4.2 on 2025-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_alter_department_code_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_of_lecture',
            field=models.IntegerField(),
        ),
    ]
