# Generated by Django 6.0.1 on 2026-01-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_alter_attendance_department_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Room', 'Room'), ('Lab', 'Lab')], max_length=10)),
                ('number', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
