# Generated by Django 4.2 on 2025-07-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_alter_result_eight_alter_result_five_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date_of_joining', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
            ],
        ),
    ]
