# Generated by Django 4.2 on 2025-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_feepayment_applied_to_semester_feepayment_is_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='applied_to_semester',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='is_advance',
        ),
    ]
