# Generated by Django 6.0.1 on 2026-01-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_lab_delete_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='attendance_pin',
            new_name='personal_pin',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='attendance_pin',
            new_name='personal_pin',
        ),
        migrations.AddField(
            model_name='student',
            name='personal_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
