# Generated by Django 4.2 on 2025-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_alter_course_no_of_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
