# Generated by Django 6.0.1 on 2026-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_rename_attendance_pin_admin_personal_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='lecture_number',
            new_name='lecture',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('college_id', 'lecture', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Pending', 'Pending')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='department',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
    ]
