# Generated by Django 4.2 on 2025-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_add',
            name='tenth_dmc',
        ),
        migrations.AddField(
            model_name='student_add',
            name='birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student_add',
            name='country',
            field=models.CharField(default='india', max_length=50),
        ),
        migrations.AddField(
            model_name='student_add',
            name='date_of_joining',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student_add',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='student_add',
            name='state_code',
            field=models.DecimalField(decimal_places=0, default='133104', max_digits=10),
        ),
        migrations.AddField(
            model_name='student_add',
            name='tenth',
            field=models.DecimalField(decimal_places=2, default='9', max_digits=10),
        ),
        migrations.AddField(
            model_name='student_add',
            name='year',
            field=models.DecimalField(decimal_places=4, default='1', max_digits=30),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='semester',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=30),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='twelth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
