# Generated by Django 4.2 on 2025-08-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_remove_feepayment_applied_to_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('college_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('date_of_joining', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('other_phone_no', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan'), ('China', 'China'), ('Other', 'Other')], max_length=30)),
                ('category', models.CharField(choices=[('Genral', 'General'), ('BC(A)', 'BC(A)'), ('BC(B)', 'BC(B)'), ('SC', 'SC'), ('ST', 'ST'), ('Others', 'Others')], max_length=10)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('NRI', 'NRI'), ('Other', 'Other')], max_length=20)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20)),
                ('adhar_no', models.BigIntegerField()),
                ('pan_no', models.CharField(max_length=20)),
                ('martial_status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='unmarried', max_length=15)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='feepayment',
            name='adjusted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.feepayment'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='is_advance_adjusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online Transfer'), ('Card', 'Credit/Debit Card'), ('Advance', 'Advance Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Partial', 'Partial Payment'), ('Advance', 'Advance Payment'), ('Adjusted', 'Advance Adjusted')], default='Paid', max_length=20),
        ),
    ]
