# Generated by Django 4.2 on 2025-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_remove_student_add_tenth_dmc_student_add_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_add',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='state_code',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student_add',
            name='tenth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
