# Generated by Django 4.2 on 2025-10-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_alter_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
