# Generated by Django 6.0.1 on 2026-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_rename_student_attendance_college_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='expired',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='qr_code',
            name='expiry_time',
            field=models.CharField(null=True),
        ),
    ]
