# Generated by Django 4.2 on 2025-08-11 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_admin_feepayment_adjusted_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feepayment',
            old_name='adjusted_to',
            new_name='adjusted_in',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='is_advance_adjusted',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Payment'), ('EXTRA', 'Extra Payment'), ('ADVANCE', 'Advance Payment'), ('ADJUSTMENT', 'Adjustment Payment')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online Transfer'), ('Card', 'Credit/Debit Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Partial', 'Partial Payment')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.student')),
            ],
        ),
    ]
