# Generated by Django 6.0.1 on 2026-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_qr_code_expired_qr_code_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_and_admin_attedance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Leave', 'Leave'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
