# Generated by Django 4.2 on 2025-07-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_alter_student_add_birth_alter_student_add_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.TextField()),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=1)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('tenth_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_add',
        ),
    ]
