# Generated by Django 4.2 on 2025-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_feepayment_due_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='adjusted_in_semester',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='adjusted_in_year',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
