# Generated by Django 4.2 on 2025-10-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_alter_feepayment_adjusted_in_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='status',
        ),
    ]
