# Generated by Django 6.0.1 on 2026-01-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_alter_faculty_and_admin_attedance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_time',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Emergency Leave', 'Emergency Leave'), ('Planned Leave', 'Planned Leave'), ('Short Leave', 'Short Leave')], max_length=50),
        ),
    ]
