# Generated by Django 4.2 on 2025-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_student_delete_student_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(default='india', max_length=50),
        ),
    ]
