# Generated by Django 4.2 on 2025-10-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0028_remove_feepayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='payment_type',
        ),
    ]
