# Generated by Django 6.0.1 on 2026-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0028_leave_leave_time_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
