# Generated by Django 5.0.2 on 2026-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_qr_code_processed_alter_qr_code_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='expiry_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
