# Generated by Django 4.2 on 2025-08-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_remove_chatroom_participants_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='chat_identifier',
            field=models.CharField(default=2, max_length=100, null=True),
        ),
    ]
