# Generated by Django 5.0.2 on 2026-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_alter_qr_code_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_time',
            field=models.IntegerField(null=True),
        ),
    ]
