# Generated by Django 5.0.2 on 2026-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_alter_leave_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_and_admin_attedance',
            name='date',
            field=models.DateField(),
        ),
    ]
