# Generated by Django 4.2 on 2025-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_alter_faculty_chat_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='chat_identifier',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
