# Generated by Django 4.2 on 2025-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_alter_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
