# Generated by Django 4.2 on 2025-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0031_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetail',
        ),
    ]
