# Generated by Django 4.2 on 2025-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0032_alter_student_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_percent',
        ),
    ]
