# Generated by Django 4.2 on 2025-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_courses_delete_student_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_of_years', models.IntegerField()),
                ('no_of_semesters', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
