# Generated by Django 4.2 on 2025-08-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_remove_chatroom_is_active_chatroom_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chat_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
