# Generated by Django 4.2 on 2025-10-31 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0033_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.userdetail'),
        ),
    ]
