# Generated by Django 4.2 on 2025-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0034_alter_student_chat_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'is_delivered'], name='newapp_mess_chat_ro_6ac45c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'is_read'], name='newapp_mess_chat_ro_6b807c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='newapp_mess_timesta_eeb70b_idx'),
        ),
    ]
