# Generated by Django 5.2.8 on 2025-11-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0035_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.course')),
            ],
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
