# Generated by Django 4.2 on 2025-08-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0035_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='followed_faculty',
            field=models.ManyToManyField(blank=True, related_name='followers', to='newapp.faculty'),
        ),
    ]
