# Generated by Django 5.2.8 on 2025-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0036_subject_details_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_details',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
