# Generated by Django 4.2 on 2025-08-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0036_student_followed_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
