# Generated by Django 4.2 on 2025-07-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0037_alter_student_course'),
    ]

    operations = [
    ]
