# Generated by Django 5.2.8 on 2025-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0037_alter_subject_details_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_details',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_details',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
