# Generated by Django 4.2 on 2025-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0038_chatroom_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='newapp_mess_chat_ro_6ac45c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='newapp_mess_chat_ro_6b807c_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='newapp_mess_timesta_eeb70b_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='chat_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='chat_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
