# Generated by Django 4.2 on 2025-07-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0038_convert_course_to_foreignkey'),
    ]

    operations = [
    ]
