# Generated by Django 5.2.8 on 2025-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0039_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='number2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='number3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='number4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number',
            name='number5',
            field=models.IntegerField(default=0),
        ),
    ]
