# Generated by Django 4.2 on 2025-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0039_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chat_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
