# Generated by Django 4.2 on 2025-08-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0040_alter_student_chat_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='chat_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
