# Generated by Django 5.2.8 on 2025-11-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0040_alter_number_number1_alter_number_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_details',
            name='serial_no',
            field=models.CharField(max_length=50),
        ),
    ]
