# Generated by Django 4.2 on 2025-07-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0040_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
