# Generated by Django 5.2.8 on 2025-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0041_alter_subject_details_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(default='Deepanshu', max_length=100)),
                ('friend_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('decision_made_at', models.DateTimeField(blank=True, null=True)),
                ('contact_option', models.CharField(blank=True, choices=[('shared_contact', 'User Shared Contact'), ('requested_contact', 'User Requested Contact')], max_length=20, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_requested_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Friendship Request',
                'verbose_name_plural': 'Friendship Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
