# Generated by Django 4.2 on 2025-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0042_faculty_add_delete_attendance_delete_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_add',
            name='category',
            field=models.CharField(choices=[('Genral', 'General'), ('BC(A)', 'BC(A)'), ('BC(B)', 'BC(B)'), ('SC', 'SC'), ('ST', 'ST'), ('Others', 'Others')], max_length=10),
        ),
    ]
