# Generated by Django 5.2.8 on 2025-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0042_friendshiprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wants_friendship', models.BooleanField(default=False)),
                ('wants_to_share_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
