# Generated by Django 5.2.8 on 2025-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0043_friendshipproposal_delete_friendshiprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshipproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Friendship Proposal', 'verbose_name_plural': 'Friendship Proposals'},
        ),
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='wants_to_share_contact',
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='contact_shared',
            field=models.BooleanField(default=False, verbose_name='Contact Shared'),
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='friend_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Friend's Name"),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='user_phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='wants_friendship',
            field=models.BooleanField(default=True, verbose_name='Wants Friendship'),
        ),
    ]
