# Generated by Django 5.2.8 on 2025-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0044_alter_friendshipproposal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='birthday_photos/')),
                ('greeting_message', models.TextField(default='Happy Birthday! Wishing you all the happiness in the world!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
