# Generated by Django 5.2.8 on 2025-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0045_birthdaygreeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='contact_shared',
        ),
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='friendshipproposal',
            name='wants_friendship',
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='contact_choice',
            field=models.CharField(choices=[('share', 'Wants to share contact'), ('request', 'Wants to get contact'), ('none', 'No contact shared')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='contact_shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes'), ('no', 'No')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='decision_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendshipproposal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='friend_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='friendshipproposal',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
