# Generated by Django 4.2 on 2025-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0046_alter_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Income',
            field=models.CharField(default='JK', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Occupation',
            field=models.CharField(default='hjb', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='adhar_no',
            field=models.BigIntegerField(default=900),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('Genral', 'General'), ('BC(A)', 'BC(A)'), ('BC(B)', 'BC(B)'), ('SC', 'SC'), ('ST', 'ST'), ('Others', 'Others')], default='HKJ', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='family_id',
            field=models.CharField(default='JHB', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='family_id_phone_no',
            field=models.CharField(default='JJ', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='jhk', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('NRI', 'NRI'), ('Other', 'Other')], default='BHJJK', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='pan_no',
            field=models.CharField(default='JHB', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(default='bkj', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='788', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], default='9OJ', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='unmarried', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.EmailField(default='M@GMAIL', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
    ]
