# Generated by Django 4.2 on 2025-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0047_student_income_student_occupation_student_adhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Income',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='Occupation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='adhar_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('Genral', 'General'), ('BC(A)', 'BC(A)'), ('BC(B)', 'BC(B)'), ('SC', 'SC'), ('ST', 'ST'), ('Others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='family_id_phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('NRI', 'NRI'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='pan_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
