# Generated by Django 4.2 on 2025-07-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0048_alter_student_income_alter_student_occupation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Income',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Occupation',
            new_name='occupation',
        ),
    ]
