# Generated by Django 5.2.8 on 2026-01-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0048_employee_biometricdata_attendancelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('random_data', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='biometricdata',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='BiometricData',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
