# Generated by Django 5.2.8 on 2026-01-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0049_qr_code_remove_attendancelog_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
