# Generated by Django 5.2.8 on 2026-01-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0050_alter_qr_code_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='time',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
