# Generated by Django 4.2 on 2025-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0051_faculty_delete_faculty_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
