# Generated by Django 4.2 on 2025-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0052_alter_student_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_id_phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
