# Generated by Django 5.2.8 on 2026-01-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0052_qr_code_date_alter_qr_code_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_code',
            name='timestamp',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qr_code',
            name='time',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
