# Generated by Django 5.2.8 on 2026-01-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0053_qr_code_timestamp_alter_qr_code_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthdayGreeting',
        ),
        migrations.DeleteModel(
            name='FriendshipProposal',
        ),
    ]
