# Generated by Django 4.2 on 2025-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0053_alter_student_family_id_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='income',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
