# Generated by Django 4.2 on 2025-08-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0055_alter_student_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
