# Generated by Django 5.2.8 on 2026-01-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0056_alter_chatroom1_options_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom1',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatroom1',
            name='members',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom1',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
