# Generated by Django 4.2 on 2025-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0056_alter_faculty_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='other_phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='state_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
