# Generated by Django 5.2.8 on 2026-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0057_remove_chatroom1_created_by_remove_chatroom1_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='attendance_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
        migrations.AddField(
            model_name='faculty',
            name='attendance_pin',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
