# Generated by Django 5.2.8 on 2026-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0058_admin_attendance_pin_faculty_attendance_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_and_Admin_Attedance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeID', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('leave_time', models.IntegerField(null=True)),
            ],
        ),
    ]
